### ISSUE TITLE
Add demo tests corresponding to each CLA in ion-core build

### ISSUE THREAD

**Issue by iondev33** [nasa-jpl/ion-core#2]
* Depending on the CLA selected, run different demo tests
* Need to add `system_up` script to the root of ion-core
* For LTP CLA, add `bench-ltp`
* For UDP CLA, add `bench-udp`
* For STCP CLA, add `bench-stcp`
* Update the make target `testcla` that determines which tests to run depending on which CLAs were built

**Comment by type6six** [comment]
closing duplicate
